default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sourceloader_dev

test:
  <<: *default
  database: sourceloader_test

production:
  <<: *default
  database: sourceloader
